version: '3.7'

services:
  mysql:
    container_name: getground_mysql_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5
    ports:
      - 3306:3306
    volumes:
      - database_mysql:/var/lib/mysql
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
    networks:
      - backend
  app:
    container_name: getground_app
    build:
      context: . 
      dockerfile: docker/deploy/Dockerfile
    restart: always
    volumes:
      - api:/usr/src/app/
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8081:8081
    networks:
      - backend
volumes:
  api:
  database_mysql:
networks:
  backend:
    driver: bridge

